# Generated by Django 4.0.6 on 2022-07-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='account_name',
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(max_length=100, null=True, verbose_name='소개'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_name',
            field=models.CharField(max_length=30, null=True, verbose_name='사용자의 이름'),
        ),
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
